import './assets/scss/app.scss'
import './assets/less/vendors/font-awesome/font-awesome.less'
import './assets/less/vendors/material-design-iconic-font/material-design-iconic-font.css'
import './assets/less/inc/progress-bar.less'
import './assets/less/inc/vendor-overrides/bootstrap-grid.less'
import './assets/less/inc/autocomplete.less'